[package]
name = "json-serialize"
version = "0.1.0"
authors = ["Shohei YOSHIDA <syohex@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version =  "1.0", features = ["derive"]}
serde_json = "1"
