[package]
name = "web-scraper01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
reqwest = {version = "0.11", features = ["blocking"]}
scraper = "0.13"
